steps:
  - id: 'Deploy image to kubernetess'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./src/deployment.yaml
    - --location=us-central1-c
    - --cluster=cluster-1
    - --project=norse-geode-306112
