  steps:
  
  - id: Generate manifest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      ls
    dir: "${_TEST}"  
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true'] 
  - id: Generate maniffest
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospring","."]
  - id: Generate maniffsesst
    name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/hellospring"]
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./deployment.yaml
    - --location=us-central1-c
    - --cluster=cluster-1
    - --project=galvanic-kit-303008
