steps:
  - id: 'build your instance'
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ['clean','package']
  - id: 'Deploy to app engine using gcloud image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test', '.' ]
  - id: 'Push image to registery'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test']
