  steps:
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true']
  - id: Generate manifest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
     sed --expression  "s@private-reg@${_TEST}/g" deployment.yaml 
  - id: Generate maniffest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
       cat deployment.yaml   
  #  dir: "src/main/java/com/mcnz/rps"
  - id: 'build your instancce'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['spring-boot:run']
    dir: "src/main/java/com/mcnz/rps"
  
  - id: 'build your instances'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['deploy']  
  #  dir: "run/helloworld"
  - id: 'Build'
    name: 'gcr.io/cloud-builders/javac'
    args: ['Game.java']
    dir: "src/main/java/com/mcnz/rps"
  artifacts:
    objects:
      location: 'gs://artifacts-bucketss/test'
      paths: ['Game.java']
