steps: 
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['sonar:sonar']        
  - id: 'Sonarqube' 
    name: 'gcr.io/practical-case-298304/testt:latest'
    args:
    - '-Dsonar.host.url=http://34.68.145.186:8010'
    - '-Dsonar.login=6c40d08c8646fef3bfcb7d2a1ae3b03d7bff5ed3'
    - '-Dsonar.projectKey=mykey'
    - '-Dsonar.qualitygate.wait=true'
    - '-Dsonar.sources=.'
  - id: 'Deploy to app engine using gcloud image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test', '.' ]
  - id: 'Push image to registery'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test']
  - id: 'Deploy image to kubernetes'
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./src
    - --image=gcr.io/$PROJECT_ID/test:latest
    - --location=us-central1-c
    - --cluster=cluster-1

