  steps:
  
  - id: Generate manifest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      ls
      mkdir test
     # sed -i 's#number#$_NETWORK_NAME#g' TanslationService.java
     # cat TanslationService.java
  - id: Generate manifests
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      ls
        
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true'] 
  - id: Generate maniffest
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospring","."]
  - id: Generate maniffsesst
    name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/hellospring"]
  - id: "Cleaning the old deployment" #This is the temporary step which will be deleted after versioning of images
    name: 'gcr.io/cloud-builders/kubectl'  
    args:
    - 'delete'
    - 'pod' 
    - '--all'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
    - 'CLOUDSDK_CORE_PROJECT=galvanic-kit-303008'
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./src/deployment.yaml
    - --location=us-central1-c
    - --cluster=cluster-1
    - --project=galvanic-kit-303008
  - id: Generate manifest test
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      rm -r output
  - id: Generate manifesst test
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      ls    
  - id: Generate manifest for ci
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
     gcloud builds submit --config ci.cloudbuild.yaml .  \
      --substitutions=_TEST="src/"
    
