steps: 
  
  - id: "run bash"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          cp src/pom.xml ./
          ls
  - id: 'build your instance'
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ['clean','package']
artifacts:
    objects:
       location: 'gs://sarthakbucket'
       paths: ["/workspace/target/roshambo.war"]   


