steps: 
  
  - id: "run bash"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
  - id: 'build your instance'
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ['clean','package']        
  - id: 'Deploy to app engine using gcloud image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test', '.' ]
  - id: 'Push image to registery'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test']
  - id: 'Deploy image to kubernetes'
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./src
    - --image=gcr.io/$PROJECT_ID/test:latest
    - --location=us-central1-c
    - --cluster=cluster-1

