steps: 
  
  - id: "run bash"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
  - id: 'build your instance'
    name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ['clean','package']
  - id: 'Sonarqube' 
    name: 'gcr.io/$PROJECT_ID/testt:latest'
    args:
     - '-Dsonar.host.url=http://34.68.145.186:8010'
     - '-Dsonar.login=6c40d08c8646fef3bfcb7d2a1ae3b03d7bff5ed3'
     - '-Dsonar.projectKey=mykey'
     - '-Dsonar.qualitygate.wait=true'
     - '-Dsonar.sources=.'  
  - id: 'Deploy to app engine using gcloud image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test', '.' ]
  - id: 'Push image to registery'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/test']
  - id: 'Deploy image to kubernetes'
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./src
    - --image=gcr.io/$PROJECT_ID/test:latest
    - --location=us-central1-c
    - --cluster=cluster-1  
artifacts:
    objects:
       location: 'gs://sarthakbucket'
       paths: ["/workspace/target/roshambo.war"]   


